### ISSUE TITLE
Masking not allowed above order 87

### ISSUE THREAD

**Issue by bprinoth** [Hoeijmakers/tayph#112]
Masking is not possible above order 87. 
It results in a bugged preview, see screenshot, and then jumps back to order 87. 

<img width="1232" alt="Screenshot 2022-07-07 at 10 43 42" src="https://user-images.githubusercontent.com/34542496/177731478-92b48517-6b68-41a8-99a1-0383c7135b40.png">

**Comment by Hoeijmakers** [comment]
This has been solved today.
