### ISSUE TITLE
calling molecfit_gui by pythonw

### ISSUE THREAD

**Issue by bprinoth** [Hoeijmakers/tayph#23]
When running molecfit_gui on Mac, the permission for using the screen has to be given. 
This is done by calling `pythonw` instead of `python3` for the gui in `telluric.py`. 

Maybe check first: Does this always work?

**Comment by Hoeijmakers** [comment]
In my case this makes it open a python 2.7 shell. On the one hand it may be good to move Molecfit back to 2.7 (the way it is provided by ESO) but on the other, it means that Tayph will have both a python 3 and a python 2 dependency.

In fact, this problem may go away when people upgrade to python 3.9:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/57099343/104347220-44555e00-54f8-11eb-81ab-1cc2f97e701c.png">

I'm tempted to force users to provide their python alias in their configuration file (which is passed to molecfit anyhows) and then we leave it up to them to make use of pythonw if they need to, which then would have to be an alias for pythonw 3.x.
