### ISSUE TITLE
Eliminate Findgen

### ISSUE THREAD

**Issue by Hoeijmakers** [Hoeijmakers/tayph#32]
functions.findgen is an IDL relic that has no place in 2021. It's simply equivalent to np.arange(N,dtype=float).

Unfortunately it's used almost everywhere. Spend a rainy afternoon with a hot chocolate to go through the code and eliminate it all over.

**Comment by bprinoth** [comment]
functions.findgen is eliminated in all files. It can now be removed from functions.py.
