### ISSUE TITLE
tapy.run.read_e2ds path is always relative even when given absolute path

### ISSUE THREAD

**Issue by thorsbro** [Hoeijmakers/tayph#45]
I did a run:

tayph.run.read_e2ds('/home/thorsbro/tayph/wasp19b/data/espresso_4', '/home/thorsbro/tayph/wasp19b/input/espresso_4', mode='ESPRESSO')

the second path was treated as a relative path and put under data/, i.e.
data/home/thorsbro/tayph/wasp19b/input/espresso_4

Interestingly enough the path to the pipeline reduction data was not prepended anything and it worked with absolute path.

**Comment by Hoeijmakers** [comment]
The second keyword is supposed to be the 'name' of a dataset, with potential subdirectories made by giving a /. I.e. WASP-123/night1, WASP-123/night2, etc. I have now modified read_e2ds to trigger an error if a user passes an absolute path or a relative path that starts with '.' or '..'. In the future, one could think of modifying Tayph such that a user has complete freedom in where the input comes from and where the output flows to. I will close this issue and open a new one as an enhancement.
