### ISSUE TITLE
tayph.run.read_e2ds save plots in pdf files

### ISSUE THREAD

**Issue by thorsbro** [Hoeijmakers/tayph#46]
Would it be possible to have the plots saved in pdf files instead of shown, perhaps controlled by an argument to the read_e2ds function, like saveplotstopdf=True

It is fine if its default false.

The plots should be saved in the same folder as the final fits files.

**Comment by Hoeijmakers** [comment]
I like plotting them to screen because the user will probably want to zoom in and inspect the spectra at high resolution to check what is going on with the velocities. Do you believe that this plot would still be useful if not zoomed in? If so, I will add this.

**Comment by thorsbro** [comment]
I am thinking on it as an option so the user can choose.

My thinking is that once the plots are closed they are gone. If saved to PDF you can always open for inspection without having to rerun the code.

**Comment by Hoeijmakers** [comment]
This is now implemented. The plot is saved to the data folder by default.
