### ISSUE TITLE
minor bug in run.check_molecfit

### ISSUE THREAD

**Issue by thorsbro** [Hoeijmakers/tayph#53]
At the end (line 1670) of the function run.check_molecfit(...) where the transmission spectrum is written the newly introduced third argument (list_of_fxc) is missing.

Compare line 1670:
tel.write_telluric_transmission_to_file(list_of_wls,list_of_trans,dp/'telluric_transmission_spectra.pkl')

With line 1627:
tel.write_telluric_transmission_to_file(list_of_wls,list_of_trans,list_of_fxc,dp/'telluric_transmission_spectra.pkl')

**Comment by Hoeijmakers** [comment]
Fixed it.
