### ISSUE TITLE
test data has hidden files

### ISSUE THREAD

**Issue by JVSeidel** [Hoeijmakers/tayph#73]
The test data from HARPS-N has two hidden files that are also downloaded into the folder. This leads tayph to crash with the warning "missing END card in header".

The issue is resolved when performing rm ._* (the start of the hidden files path) in the terminal in the folder where the test data is stored. Best would be to delete the hidden files directly.

Cheers,

Julia

**Comment by Hoeijmakers** [comment]
I was unable to reproduce this issue exactly. I chose to fix this implicitly by reading only files that are of FITS extension, and that are not hidden. That's generally the behaviour you'd expect, anyway.
