### ISSUE TITLE
Documentation - molecfit

### ISSUE THREAD

**Issue by JVSeidel** [Hoeijmakers/tayph#74]
The documentation ends rather abruptly after the application of molecfit.

I think two small fixes are needed here to complete the documentation for first-time users (it's me, I'm talking about me).

Assuming one already has telluric corrected files, from molecfit or elsewhere, what is the folder/file structure one has to generate to feed those into tayph. How does one then run tayph on these telluric corrected spectra? (I'm assuming it will skip the testing steps etc if it already gets telluric corrected files?)

Cheers,

Julia

**Comment by Hoeijmakers** [comment]
This has been added.
